// Copyright 2026 The Casdoor Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package casdoorsdk

import (
	"encoding/json"
	"fmt"
	"strconv"
)

// Key has the same definition as https://github.com/casdoor/casdoor/blob/master/object/key.go
type Key struct {
	Owner       string `xorm:"varchar(100) notnull pk" json:"owner"`
	Name        string `xorm:"varchar(100) notnull pk" json:"name"`
	CreatedTime string `xorm:"varchar(100)" json:"createdTime"`
	UpdatedTime string `xorm:"varchar(100)" json:"updatedTime"`
	DisplayName string `xorm:"varchar(100)" json:"displayName"`

	// Type indicates the scope this key belongs to: "Organization", "Application", "User", or "General"
	Type         string `xorm:"varchar(100)" json:"type"`
	Organization string `xorm:"varchar(100)" json:"organization"`
	Application  string `xorm:"varchar(100)" json:"application"`
	User         string `xorm:"varchar(100)" json:"user"`

	AccessKey    string `xorm:"varchar(100) index" json:"accessKey"`
	AccessSecret string `xorm:"varchar(100)" json:"accessSecret"`

	ExpireTime string `xorm:"varchar(100)" json:"expireTime"`
	State      string `xorm:"varchar(100)" json:"state"`
}

// GetGlobalKeys returns the keys of all organizations.
func (c *Client) GetGlobalKeys() ([]*Key, error) {
	url := c.GetUrl("get-global-keys", nil)

	bytes, err := c.DoGetBytes(url)
	if err != nil {
		return nil, err
	}

	var keys []*Key
	err = json.Unmarshal(bytes, &keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

// GetKeys returns the keys of the organization of the client. The access secrets are masked.
func (c *Client) GetKeys() ([]*Key, error) {
	queryMap := map[string]string{
		"owner": c.OrganizationName,
	}

	url := c.GetUrl("get-keys", queryMap)

	bytes, err := c.DoGetBytes(url)
	if err != nil {
		return nil, err
	}

	var keys []*Key
	err = json.Unmarshal(bytes, &keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (c *Client) GetPaginationKeys(p int, pageSize int, queryMap map[string]string) ([]*Key, int, error) {
	queryMap["owner"] = c.OrganizationName
	queryMap["p"] = strconv.Itoa(p)
	queryMap["pageSize"] = strconv.Itoa(pageSize)

	url := c.GetUrl("get-keys", queryMap)

	response, err := c.DoGetResponse(url)
	if err != nil {
		return nil, 0, err
	}

	dataBytes, err := json.Marshal(response.Data)
	if err != nil {
		return nil, 0, err
	}

	var keys []*Key
	err = json.Unmarshal(dataBytes, &keys)
	if err != nil {
		return nil, 0, err
	}

	return keys, int(response.Data2.(float64)), nil
}

// GetKey returns the key with its access secret in plain text.
func (c *Client) GetKey(name string) (*Key, error) {
	queryMap := map[string]string{
		"id": c.GetId(name),
	}

	url := c.GetUrl("get-key", queryMap)

	bytes, err := c.DoGetBytes(url)
	if err != nil {
		return nil, err
	}

	var key *Key
	err = json.Unmarshal(bytes, &key)
	if err != nil {
		return nil, err
	}
	return key, nil
}

// AddKey adds a key. The access key and the access secret are generated by Casdoor, the
// values in the given key are ignored. Use GetKey to read the generated ones.
func (c *Client) AddKey(key *Key) (bool, error) {
	_, affected, err := c.modifyKey("add-key", key)
	return affected, err
}

// UpdateKey updates a key. The access key and the access secret can't be changed, the values
// in the given key are ignored.
func (c *Client) UpdateKey(key *Key) (bool, error) {
	_, affected, err := c.modifyKey("update-key", key)
	return affected, err
}

func (c *Client) DeleteKey(key *Key) (bool, error) {
	_, affected, err := c.modifyKey("delete-key", key)
	return affected, err
}

func (k Key) GetId() string {
	return fmt.Sprintf("%s/%s", k.Owner, k.Name)
}
