// Copyright 2026 The Casdoor Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package casdoorsdk

import (
	"testing"
	"time"
)

func TestKey(t *testing.T) {
	InitConfig(TestCasdoorEndpoint, TestClientId, TestClientSecret, TestJwtPublicKey, TestCasdoorOrganization, TestCasdoorApplication)

	name := getRandomName("unit_test_key")
	key := &Key{
		Owner:        TestCasdoorOrganization,
		Name:         name,
		CreatedTime:  time.Now().Format(time.RFC3339),
		DisplayName:  "Test Key",
		Type:         "Organization",
		Organization: TestCasdoorOrganization,
		AccessKey:    getRandomName("ak"),
		AccessSecret: "test-secret-value",
		State:        "Active",
	}

	affected, err := AddKey(key)
	if err != nil {
		t.Fatalf("Failed to add key: %v", err)
	}
	if !affected {
		t.Fatalf("Expected AddKey to affect a row")
	}
	defer func() {
		_, _ = DeleteKey(&Key{Owner: TestCasdoorOrganization, Name: name})
	}()

	// Test GetKey
	got, err := GetKey(name)
	if err != nil {
		t.Fatalf("Failed to get key: %v", err)
	}
	if got == nil || got.Type != "Organization" || got.Owner != key.Owner || got.DisplayName != key.DisplayName {
		t.Fatalf("Retrieved key does not match added key: %+v", got)
	}

	// Casdoor generates the credentials and ignores the given ones
	if got.AccessKey == "" || got.AccessKey == key.AccessKey || got.AccessSecret == "" || got.AccessSecret == key.AccessSecret {
		t.Fatalf("Expected the credentials to be generated by Casdoor: %+v", got)
	}
	accessKey, accessSecret := got.AccessKey, got.AccessSecret

	// Test GetKeys, the access secret is masked
	keys, err := GetKeys()
	if err != nil {
		t.Fatalf("Failed to get keys: %v", err)
	}
	if k := findKey(keys, name); k == nil {
		t.Fatalf("The added key is not in GetKeys")
	} else if k.AccessSecret != "***" {
		t.Fatalf("Expected the access secret to be masked, got %q", k.AccessSecret)
	}

	// Test GetGlobalKeys, it includes the keys of the other organizations
	otherName := getRandomName("unit_test_key")
	_, err = AddKey(&Key{Owner: "built-in", Name: otherName, Type: "Organization", Organization: "built-in", State: "Active"})
	if err != nil {
		t.Fatalf("Failed to add the key of another organization: %v", err)
	}
	defer func() {
		_, _ = DeleteKey(&Key{Owner: "built-in", Name: otherName})
	}()

	globalKeys, err := GetGlobalKeys()
	if err != nil {
		t.Fatalf("Failed to get global keys: %v", err)
	}
	if findKey(globalKeys, name) == nil || findKey(globalKeys, otherName) == nil {
		t.Fatalf("The added keys are not in GetGlobalKeys")
	}
	if findKey(keys, otherName) != nil {
		t.Fatalf("GetKeys must only return the keys of the organization of the client")
	}

	// Test GetPaginationKeys
	pageKeys, total, err := GetPaginationKeys(1, 100, map[string]string{"field": "name", "value": name})
	if err != nil {
		t.Fatalf("Failed to get pagination keys: %v", err)
	}
	if total != 1 || len(pageKeys) != 1 || pageKeys[0].Name != name {
		t.Fatalf("Unexpected pagination result: total=%d keys=%d", total, len(pageKeys))
	}

	// Test UpdateKey
	got.DisplayName = "Test Key Updated"
	got.State = "Suspended"
	got.AccessKey, got.AccessSecret = "changed", "changed"
	if _, err = UpdateKey(got); err != nil {
		t.Fatalf("Failed to update key: %v", err)
	}
	got, err = GetKey(name)
	if err != nil {
		t.Fatalf("Failed to get key: %v", err)
	}
	if got.DisplayName != "Test Key Updated" || got.State != "Suspended" {
		t.Fatalf("The key was not updated: %+v", got)
	}
	if got.AccessKey != accessKey || got.AccessSecret != accessSecret {
		t.Fatalf("Expected the credentials to stay the same after the update: %+v", got)
	}

	// Test DeleteKey
	affected, err = DeleteKey(got)
	if err != nil {
		t.Fatalf("Failed to delete key: %v", err)
	}
	if !affected {
		t.Fatalf("Expected DeleteKey to affect a row")
	}
	deleted, err := GetKey(name)
	if err != nil {
		t.Fatalf("Failed to get the deleted key: %v", err)
	}
	if deleted != nil {
		t.Fatalf("Failed to delete key, it still exists")
	}
}

func findKey(keys []*Key, name string) *Key {
	for _, key := range keys {
		if key.Name == name {
			return key
		}
	}
	return nil
}
